import { NextResponse } from "next/server";

import { getPrisma } from "@/lib/prisma";
import { ensureCurrentUserProfile } from "@/lib/user-profile";

export async function GET() {
  const userProfile = await ensureCurrentUserProfile();

  if (!userProfile) {
    return NextResponse.json({ error: "Sign in required." }, { status: 401 });
  }

  const prisma = getPrisma();
  const [
    settings,
    onboardingState,
    userGoals,
    attempts,
    aiReviews,
    mistakes,
    flashcards,
    reviewLogs,
    battles,
    quests,
    achievements,
    recommendations,
    interviews,
    codeSubmissions,
    codeRuns,
    voiceTurns,
    voiceFeedback,
    learningPlans,
    diagnosticAssessments,
    userFeedback,
  ] = await Promise.all([
    prisma.userSettings.findUnique({
      where: { userProfileId: userProfile.id },
      omit: { id: true, userProfileId: true },
    }),
    prisma.onboardingState.findUnique({
      where: { userProfileId: userProfile.id },
      omit: { id: true, userProfileId: true },
    }),
    prisma.userGoal.findMany({
      where: { userProfileId: userProfile.id },
      select: {
        goalType: true,
        title: true,
        targetDate: true,
        status: true,
        createdAt: true,
        updatedAt: true,
      },
      orderBy: { createdAt: "desc" },
    }),
    prisma.attempt.findMany({
      where: { userProfileId: userProfile.id },
      select: {
        problem: { select: { title: true, difficulty: true } },
        selectedPattern: { select: { name: true } },
        correctPattern: { select: { name: true } },
        wasPatternCorrect: true,
        solvedStatus: true,
        timeSpentMinutes: true,
        confidence: true,
        reflection: true,
        createdAt: true,
      },
      orderBy: { createdAt: "desc" },
    }),
    prisma.aIReview.findMany({
      where: { userProfileId: userProfile.id },
      select: {
        problem: { select: { title: true, difficulty: true } },
        pattern: { select: { name: true } },
        patternScore: true,
        implementationScore: true,
        complexityScore: true,
        explanationScore: true,
        feedbackSummary: true,
        strengths: true,
        weaknesses: true,
        complexityFeedback: true,
        suggestedNextStep: true,
        createdAt: true,
      },
      orderBy: { createdAt: "desc" },
    }),
    prisma.mistake.findMany({
      where: { userProfileId: userProfile.id },
      select: {
        problem: { select: { title: true, difficulty: true } },
        pattern: { select: { name: true } },
        mistakeType: true,
        description: true,
        correction: true,
        reviewDueAt: true,
        lastReviewedAt: true,
        intervalDays: true,
        easeFactor: true,
        repetitions: true,
        lapses: true,
        status: true,
        createdAt: true,
      },
      orderBy: { createdAt: "desc" },
    }),
    prisma.flashcard.findMany({
      where: { userProfileId: userProfile.id },
      select: {
        pattern: { select: { name: true } },
        front: true,
        back: true,
        reviewDueAt: true,
        lastReviewedAt: true,
        intervalDays: true,
        easeFactor: true,
        repetitions: true,
        lapses: true,
        status: true,
        createdAt: true,
      },
      orderBy: { createdAt: "desc" },
    }),
    prisma.reviewLog.findMany({
      where: { userProfileId: userProfile.id },
      select: {
        itemType: true,
        rating: true,
        previousIntervalDays: true,
        nextIntervalDays: true,
        reviewedAt: true,
      },
      orderBy: { reviewedAt: "desc" },
    }),
    prisma.battle.findMany({
      where: { userProfileId: userProfile.id },
      select: {
        battleType: true,
        title: true,
        targetPattern: { select: { name: true } },
        status: true,
        startedAt: true,
        completedAt: true,
        totalRounds: true,
        xpEarned: true,
        result: true,
        createdAt: true,
        rounds: {
          select: {
            roundNumber: true,
            roundType: true,
            problem: { select: { title: true, difficulty: true } },
            expectedPattern: { select: { name: true } },
            completedAt: true,
          },
          orderBy: { roundNumber: "asc" },
        },
      },
      orderBy: { createdAt: "desc" },
    }),
    prisma.quest.findMany({
      where: { userProfileId: userProfile.id },
      select: {
        questType: true,
        title: true,
        description: true,
        targetCount: true,
        currentCount: true,
        xpReward: true,
        status: true,
        date: true,
        completedAt: true,
        createdAt: true,
      },
      orderBy: { createdAt: "desc" },
    }),
    prisma.userAchievement.findMany({
      where: { userProfileId: userProfile.id },
      select: {
        earnedAt: true,
        achievement: {
          select: {
            key: true,
            name: true,
            description: true,
            icon: true,
            xpReward: true,
          },
        },
      },
      orderBy: { earnedAt: "desc" },
    }),
    prisma.recommendation.findMany({
      where: { userProfileId: userProfile.id },
      select: {
        recommendationType: true,
        priority: true,
        status: true,
        title: true,
        reason: true,
        targetPattern: { select: { name: true } },
        secondaryPattern: { select: { name: true } },
        problem: { select: { title: true, difficulty: true } },
        battleType: true,
        expiresAt: true,
        createdAt: true,
        updatedAt: true,
        feedback: {
          select: {
            feedbackType: true,
            note: true,
            createdAt: true,
          },
          orderBy: { createdAt: "desc" },
        },
      },
      orderBy: { createdAt: "desc" },
    }),
    prisma.interviewSession.findMany({
      where: { userProfileId: userProfile.id },
      select: {
        interviewType: true,
        status: true,
        title: true,
        targetPattern: { select: { name: true } },
        difficultyTarget: true,
        durationMinutes: true,
        startedAt: true,
        completedAt: true,
        overallScore: true,
        communicationScore: true,
        patternRecognitionScore: true,
        problemSolvingScore: true,
        implementationScore: true,
        testingScore: true,
        complexityScore: true,
        timeManagementScore: true,
        result: true,
        rounds: {
          select: {
            roundNumber: true,
            status: true,
            problem: { select: { title: true, difficulty: true } },
            selectedPattern: { select: { name: true } },
            correctPattern: { select: { name: true } },
            patternExplanation: true,
            approachText: true,
            codeText: true,
            testCasesText: true,
            complexityText: true,
            startedAt: true,
            completedAt: true,
          },
          orderBy: { roundNumber: "asc" },
        },
        messages: {
          select: {
            role: true,
            phase: true,
            content: true,
            createdAt: true,
          },
          orderBy: { createdAt: "asc" },
        },
        feedbackRecords: {
          select: {
            summary: true,
            strengths: true,
            weaknesses: true,
            rubric: true,
            followUpRecommendations: true,
            createdAt: true,
          },
          orderBy: { createdAt: "desc" },
        },
        rubricScores: {
          select: {
            category: true,
            score: true,
            notes: true,
            createdAt: true,
          },
          orderBy: { createdAt: "desc" },
        },
      },
      orderBy: { createdAt: "desc" },
    }),
    prisma.codeSubmission.findMany({
      where: { userProfileId: userProfile.id },
      select: {
        problem: { select: { title: true, difficulty: true } },
        language: true,
        code: true,
        status: true,
        createdAt: true,
        updatedAt: true,
      },
      orderBy: { createdAt: "desc" },
    }),
    prisma.codeRun.findMany({
      where: { userProfileId: userProfile.id },
      select: {
        codeSubmission: {
          select: {
            problem: { select: { title: true, difficulty: true } },
            language: true,
            status: true,
          },
        },
        runType: true,
        status: true,
        stdout: true,
        stderr: true,
        compileOutput: true,
        errorMessage: true,
        runtimeMs: true,
        memoryKb: true,
        createdAt: true,
        testResults: {
          select: {
            name: true,
            inputJson: true,
            expectedOutputJson: true,
            actualOutputJson: true,
            passed: true,
            stdout: true,
            stderr: true,
            errorMessage: true,
            runtimeMs: true,
            createdAt: true,
          },
          orderBy: { createdAt: "asc" },
        },
      },
      orderBy: { createdAt: "desc" },
    }),
    prisma.voiceTurn.findMany({
      where: {
        interviewSession: {
          userProfileId: userProfile.id,
        },
      },
      select: {
        phase: true,
        speaker: true,
        transcript: true,
        durationMs: true,
        startedAt: true,
        endedAt: true,
        createdAt: true,
        interviewSession: {
          select: {
            title: true,
          },
        },
      },
      orderBy: { createdAt: "desc" },
    }),
    prisma.voiceFeedback.findMany({
      where: { userProfileId: userProfile.id },
      select: {
        interviewSession: {
          select: {
            title: true,
          },
        },
        clarityScore: true,
        structureScore: true,
        concisenessScore: true,
        confidenceScore: true,
        technicalExplanationScore: true,
        summary: true,
        strengths: true,
        weaknesses: true,
        suggestedPractice: true,
        createdAt: true,
      },
      orderBy: { createdAt: "desc" },
    }),
    prisma.learningPlan.findMany({
      where: { userProfileId: userProfile.id },
      select: {
        title: true,
        goal: true,
        status: true,
        startDate: true,
        endDate: true,
        steps: {
          select: {
            dayIndex: true,
            stepType: true,
            title: true,
            targetPattern: { select: { name: true } },
            problem: { select: { title: true } },
            targetCount: true,
            status: true,
            dueDate: true,
            completedAt: true,
          },
          orderBy: [{ dayIndex: "asc" }, { createdAt: "asc" }],
        },
      },
      orderBy: { createdAt: "desc" },
    }),
    prisma.diagnosticAssessment.findMany({
      where: { userProfileId: userProfile.id },
      select: {
        status: true,
        startedAt: true,
        completedAt: true,
        overallLevel: true,
        recommendedStartPattern: { select: { name: true } },
        questions: {
          select: {
            questionType: true,
            prompt: true,
            selectedAnswer: true,
            correctAnswer: true,
            wasCorrect: true,
            confidence: true,
            createdAt: true,
          },
          orderBy: { createdAt: "asc" },
        },
      },
      orderBy: { createdAt: "desc" },
    }),
    prisma.userFeedback.findMany({
      where: { userProfileId: userProfile.id },
      select: {
        feedbackType: true,
        pagePath: true,
        message: true,
        rating: true,
        metadata: true,
        status: true,
        createdAt: true,
        updatedAt: true,
      },
      orderBy: { createdAt: "desc" },
    }),
  ]);

  return NextResponse.json(
    {
      exportedAt: new Date().toISOString(),
      userProfile: {
        displayName: userProfile.displayName,
        createdAt: userProfile.createdAt,
        updatedAt: userProfile.updatedAt,
      },
      userSettings: settings,
      onboardingState,
      userGoals,
      attempts,
      aiReviews,
      mistakes,
      flashcards,
      reviewLogs,
      battles,
      quests,
      achievements,
      recommendations,
      interviews,
      codeSubmissions,
      codeRuns,
      voiceTurns,
      voiceFeedback,
      learningPlans,
      diagnosticAssessments,
      userFeedback,
    },
    {
      headers: {
        "Cache-Control": "no-store",
        "Content-Disposition": 'attachment; filename="patternforge-data.json"',
      },
    },
  );
}
